### ISSUE TITLE
Cannot import name literal_eval in python 2.7.6 running on 64-bit Ubuntu 14.04

### ISSUE THREAD

**Issue by banescusebi** [JonathanSalwan/Tigress_protection#1]
Hi,

I'm trying to run `./solve-vm.py ./obfuscated_binaries/tigress-0-challenge-0` but I get the following error:

 `./solve-vm.py:432: SyntaxWarning: name 'VM_INPUT' is assigned to before global declaration
  global VM_INPUT
Traceback (most recent call last):
  File "./solve-vm.py", line 14, in <module>
    from arybo.tools.triton_ import tritonexprs2arybo, tritonast2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/__init__.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/arybo/tools/petanque.py", line 29, in <module>
  File "/usr/local/lib/python2.7/dist-packages/networkx/__init__.py", line 87, in <module>
    import networkx.readwrite
  File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/__init__.py", line 14, in <module>
    from networkx.readwrite.gml import *
  File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/gml.py", line 42, in <module>
    from ast import literal_eval
ImportError: cannot import name literal_eval`

Any idea as to what is causing this and how I could get around this issue?

Thanks,
Sebastian

**Comment by aguinet** [comment]
Hello again sebastian :)

This error is because you use on old version of Triton. This has been fixed this commit https://github.com/JonathanSalwan/Triton/pull/388/commits/6fbdf2ea97cdaf460a5388c279e9b47093e3048e (see the issue #388).

As Jonathan said in the readme, you need to install the branch dev-319-bis of triton, which has this issue fixed (among other things :)).

**Comment by JonathanSalwan** [comment]
`dev-319-bis` is used to solve VM-4, however you can use `master` to solve VM-{0,1,2,3} but as Adrien said you must be up-to-date =).

**Comment by banescusebi** [comment]
Thanks for your replies! I had installed the latest version of Triton, but somehow in my virtual environment the older one was being used. Anyway, I've updated Triton and switched to its master branch and the `ImportError: cannot import name literal_eval` is gone. However, now I get the following error:

`./solve-vm.py:432: SyntaxWarning: name 'VM_INPUT' is assigned to before global declaration
  global VM_INPUT
Traceback (most recent call last):
  File "./solve-vm.py", line 14, in <module>
    from arybo.tools.triton_ import tritonexprs2arybo, tritonast2arybo
ImportError: cannot import name tritonexprs2arybo`

Any other suggestions?

**Comment by JonathanSalwan** [comment]
> `ImportError: cannot import name tritonexprs2arybo`

Because you don't use the branch `feature/exprs` of Arybo.

**Comment by banescusebi** [comment]
Yes. I mean: `git branch` shows me that I am on `* feature/exprs` and then I installed arybo via `python setup.py install` in my virtualenv.

**Comment by aguinet** [comment]
Did you install arybo system-wide using pip previously? Mabe the wrong version is used.
Can you launch python inside your virtualenv and do:

```
$ python
>>> import arybo
>>> arybo.__file__
```

and print the output.

Thanks!

**Comment by banescusebi** [comment]
@aguinet you're right system-wide installation was the problem. Thanks a lot for your help guys!
