### ISSUE TITLE
script hangs and accuracy issue

### ISSUE THREAD

**Issue by CoolTomatos** [JonathanSalwan/Tigress_protection#10]
# Hangs
Earlier I had a problem when running `solve-vm.py` against `tigress-3-challenge-0`, it hung after printing `[+] Asking for a new input...`. 
You told me to change `OPAQUE` from `False` into `True` (https://github.com/JonathanSalwan/Tigress_protection/issues/8#issuecomment-482829334).
But after doing that, it still hangs. And this time it hangs when converting symbolic expressions to an LLVM module. Please help.

# Accuracy
|      |    VM-0 |    VM-1 |    VM-2 |    VM-3 |    VM-4 |
|------|--------:|--------:|--------:|--------:|--------:|
| 0000 | 100.00% | 100.00% |  37.02% | 100.00% |  89.35% |
| 0001 | 100.00% |  62.45% | 100.00% | 100.00% | 100.00% |
| 0002 |  96.42% |  69.83% | 100.00% |  76.38% | 100.00% |

I got the above accuracies with `testing-equality.py` for the first three tigress challenges that the `solve-vm.py` managed to finish execution. In the paper it said that it should solve these challenges precisely. But 37.02% seems a bit off. Was there anything wrong in my setup?

#### Thanks in Advance

**Comment by JonathanSalwan** [comment]
* 0000-4: I've 100% with OPAQUE = False
* 0001-1: I've 100% with OPAQUE = False
* 0002-0: I've 100% with OPAQUE = False
* 0002-1: I've 100% with OPAQUE = False
* 0002-3: I've 100% with OPAQUE = False

Regarding 000-2 it seems there is something broken... I'll check that when I get spare time.

**Comment by CoolTomatos** [comment]
@JonathanSalwan thanks for the quick reply.
I reran them with `OPAQUE = False` a few times.
All the other ones managed to achieve 100% except 0002-0, which can only achieve around 96%

**Comment by JonathanSalwan** [comment]
Mmmh weird, this is what I'm getting on my machine:

```sh
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
```

**Comment by CoolTomatos** [comment]
```
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0 | grep 'Success:'
[+] Success: 96.45
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0 | grep 'Success:'
[+] Success: 96.33
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0 | grep 'Success:'
[+] Success: 96.50
$ ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0 | grep 'Success:'
[+] Success: 95.50
```
I can't run it on my machine. Above is what I got with docker.

**Comment by JonathanSalwan** [comment]
Your `./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated` file comes from your own generation or comes from the repository?

**Comment by CoolTomatos** [comment]
> Your `./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated` file comes from your own generation or comes from the repository?

it was generated after I ran `solve-vm.py` myself.

**Comment by JonathanSalwan** [comment]
Can you give me a number which not `Success` for this binary?

**Comment by CoolTomatos** [comment]
```
[-] Invalid with 9400862132345225557
[-] Invalid with 2675574437834387124
[-] Invalid with 2444561900311750446
[-] Invalid with 2302332095724163490
[-] Invalid with 2338122277057763437
[-] Invalid with 18275837737427308904
[-] Invalid with 12294231336512261197
```

**Comment by JonathanSalwan** [comment]
```
$ ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated 9400862132345225557
9445672550742213316
$ ./tigress-challenges/tigress-2-challenge-0 9400862132345225557
9445672550742213316

$ ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated 12294231336512261197
11671560219174667572
$ ./tigress-challenges/tigress-2-challenge-0 12294231336512261197
11671560219174667572
```

Mmmh I don't know where the issue may come from. Looks good for me. Maybe an issue on clang? My Clang's version is `clang version 6.0.1 (tags/RELEASE_601/final)`.

**Comment by CoolTomatos** [comment]
```
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
that's the clang bundled inside the docker image you provided.

**Comment by JonathanSalwan** [comment]
Well, i'm not using Docker and know nothing about how Docker works :). If it's related to Docker maybe you should ping @deepsadhi who added this Docker image.

**Comment by JonathanSalwan** [comment]
Also, if you modified the Docker image to make it works properly, please send me PR so that others ppl can benefit :).

**Comment by CoolTomatos** [comment]
> Also, if you modified the Docker image to make it works properly, please send me PR so that others ppl can benefit :).

I just uncommented https://github.com/JonathanSalwan/Tigress_protection/blob/e38b89c59f3188dcf15037ffac5a4af0ba87f0d0/Dockerfile#L28-L30
and then commented out https://github.com/JonathanSalwan/Tigress_protection/blob/e38b89c59f3188dcf15037ffac5a4af0ba87f0d0/Dockerfile#L31-L34

**Comment by CoolTomatos** [comment]
I am not very handy with docker as well. Didn't figure out how to replace clang 3.8 with 6.0 for the project.
; (

What OS and what version are you using may I ask?

**Comment by JonathanSalwan** [comment]
> What OS and what version are you using may I ask?

A Gentoo.

**Comment by deepsadhi** [comment]
I don't think it's clang version issue. I am using `Docker` on `Arch Linux`. Here's output on my machine
```
root@9ab6528e26f5:~/research/tools/Tigress_protection# ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
root@9ab6528e26f5:~/research/tools/Tigress_protection# ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
root@9ab6528e26f5:~/research/tools/Tigress_protection# ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
root@9ab6528e26f5:~/research/tools/Tigress_protection# ./scripts/testing_equality.py ./deobfuscated_binaries/tigress-2-challenge-0.deobfuscated ./tigress-challenges/tigress-2-challenge-0  | grep 'Success:'
[+] Success: 100.00
```

**Comment by deepsadhi** [comment]
@CoolTomatos Here's updated version of `Dockerfile` with `clang-6.0`. Let me know if it solves your issue.
[https://github.com/deepsadhi/Tigress_protection/blob/clang/Dockerfile](https://github.com/deepsadhi/Tigress_protection/blob/clang/Dockerfile)

**Comment by CoolTomatos** [comment]
@JonathanSalwan I am sorry earlier I replied the wrong fix for the triton version in the dockerfile. I deleted that commend right after I realised it was wrong. but you were too fast and already pushed it to the master branch. So dockerfile in the master branch is broken now. The problem is that there is not setup.py in the triton repo. I will make a pull request regarding this.

@deepsadhi you are right, it is not because of the clang version. I built a new image from your new Dockerfile and with the provided Deobfuscated binary, it gave an accuracy of 96% still.

**Comment by CoolTomatos** [comment]
@deepsadhi 
>... on `Arch Linux`...

I mean, you are using Arch yourself and the docker image you pushed is Ubuntu... No wonder it won't work...

**Comment by CoolTomatos** [comment]
@JonathanSalwan can you please shed some light on why the converting part is taking forever after setting `OPAQUE` to `True`?
Thanks.

**Comment by JonathanSalwan** [comment]
what binary?

**Comment by JonathanSalwan** [comment]
it's quick speed on my side.

**Comment by CoolTomatos** [comment]
> what binary?

`tigress-3-challenge-0` with `OPAQUE = True`

**Comment by JonathanSalwan** [comment]
Indeed, looks like it takes time, maybe a loop in Arybo... You know, I did this challenge +2 years ago and there are a lots of modifications added in Triton and Arybo since... I'm always trying to keep this script up- to-date but I will not do that for the rest of my life :). What are you looking for reproducing the analysis? Is it for a proof or for results? If it's for results they are already pushed.

**Comment by deepsadhi** [comment]
@CoolTomatos Yup I am using `Ubuntu 16.04` in container.
@JonathanSalwan  It's working perfectly in my side too.

**Comment by CoolTomatos** [comment]
>  It's working perfectly in my side too.

I kinda doubt that, because with [your dockerfile](https://github.com/deepsadhi/Tigress_protection/blob/clang/Dockerfile), `solve-vm.py` can't even run.

**Comment by deepsadhi** [comment]
@CoolTomatos Actually I had created [Dockerfile](https://github.com/deepsadhi/Tigress_protection/blob/clang/Dockerfile) with `clang-6.0` just for you. I haven't tested it. 
The tool is working perfectly on my machine with original [Dockerfile](https://github.com/JonathanSalwan/Tigress_protection/blob/master/Dockerfile).

**Comment by CoolTomatos** [comment]
@deepsadhi pal, I really appreciate your help. I might sound a bit hostile but I mean no offence.

But to state the facts, it was confirmed in #7 and https://github.com/JonathanSalwan/Tigress_protection/issues/8#issuecomment-482697132 that the archived version of triton in your [original Dockerfile](https://github.com/deepsadhi/Tigress_protection/blob/master/Dockerfile) doesn't work with the master version of Arybo.
In your [change for `clang-6.0`](https://github.com/deepsadhi/Tigress_protection/blob/clang/Dockerfile), it still curls the archived version of triton, so I have to assume that you weren't aware of the discussion in #7 and #8 and you weren't aware of this dependency issue.
Now the [version in master branch](https://github.com/JonathanSalwan/Tigress_protection/blob/master/Dockerfile) works because I changed that in #11.

---
> It's working perfectly in my side too.

I kinda doubted that because:
- if it was working perfectly with your version of Dockerfile, you'd run into the dependency issue and get error during `solve-vm.py`. You wouldn't even come to `testing-equality.py`
- if it was working perfectly with the master version of Dockerfile, the result is simply just not 100.00. We are reproducing this for a course. My teammates and classmates who have actually tested it, all got a result around 95-96 with the master version of Dockerfile.

**Comment by deepsadhi** [comment]
@CoolTomatos I can understand, sorry about it. I should have properly tested before pushing any code. I am in my end of the semester, so having hard time to manage time. 

**Regarding original [Dockerfile](https://github.com/JonathanSalwan/Tigress_protection/blob/master/Dockerfile)**
I am glad you solved the issue. I had used the same instructions which you are using now https://github.com/JonathanSalwan/Tigress_protection/pull/11/files. @JonathanSalwan recommend me to use `Trition-version` instead of downloading direct from `master` branch. Here's his [comment](https://github.com/JonathanSalwan/Tigress_protection/pull/5#issuecomment-461895779). I would also recommend to use latest version of Triton instead directly downloading form `master` branch. @JonathanSalwan correct me if I am wrong.

**Regarding [Dockerfile](https://github.com/deepsadhi/Tigress_protection/blob/clang/Dockerfile) I had created**
Let's ignore this file. I tried to create image using `clang-6.0`. But `z3` didn't compile, so I stopped working on it.
```
 cd /usr/bin && ln -s clang-6.0 clang && ln -s clang++-6.0 clang++
```

**Comment by JonathanSalwan** [comment]
> Here's his comment. I would also recommend to use latest version of Triton instead directly downloading form master branch. @JonathanSalwan correct me if I am wrong.

Well, if we do that we have to keep this repository (`solve-vm.py`) up-to-date with latest version of all dependencies (triton, lief, arybo, llvmlite...). Hardcoding versions of all dependencies in a dockerfile allows users to reproduce our experimentations even in 10 years from now and without modifying `solve-vm.py` :).

My two cents,

**Comment by CoolTomatos** [comment]
> Hardcoding versions of all dependencies in a dockerfile allows users to reproduce our experimentations even in 10 years from now and without modifying `solve-vm.py` :).

The thing is that previously, version of Triton iswashardcoded in the dockerfile, but not Arybo. that's why #7 happened I guess.
