### ISSUE TITLE
AttributeError: 'TritonContext' object has no attribute 'setMode'

### ISSUE THREAD

**Issue by yumouse** [JonathanSalwan/Tigress_protection#13]
I am using Ubuntu 16.04 and when executing './solve-vm.py ./tigress-challenges/tigress-0-challenge-0' , I got error like this:
Traceback (most recent call last):
  File "./solve-vm.py", line 754, in <module>
    retValue  = main()
  File "./solve-vm.py", line 636, in main
    ctx.setMode(MODE.ALIGNED_MEMORY, True)
AttributeError: 'TritonContext' object has no attribute 'setMode'

I installed Triton step by step according to these instructions:
$ git clone https://github.com/JonathanSalwan/Triton.git
$ cd Triton
$ mkdir build
$ cd build
$ cmake ..
$ sudo make -j2 install

And I installed libz3 by 'pip install z3-solver'
I am confused by this error, please help me! Thx in advance!

**Comment by JonathanSalwan** [comment]
Please git pull the Triton's branch `dev-v0.8`.
