### ISSUE TITLE
Solve-vm.py should be modified

### ISSUE THREAD

**Issue by yumouse** [JonathanSalwan/Tigress_protection#15]
Hello, I run './solve-vm.py ......' successfully with the help of the specific version of dependencies you mentioned before.

But, there is a problem that in the line 618 of solve-vm.py, the function call ctx.getSymbolicVariableFromId should be ctx.getSymbolicVariable. Except that, all things go well.

Thx for your help!

**Comment by JonathanSalwan** [comment]
Thanks! Pushed :)
