### ISSUE TITLE
solve-vm.py running fail

### ISSUE THREAD

**Issue by jacktang310** [JonathanSalwan/Tigress_protection#2]
Hi, 
   Triton is very cool. I played with it. But I encounter one issue. I look forward to eagerly your answer. I install the master branch Triton , the  branch feature/exprs of Arybo, the master branch of llvmlite. All is OK.  but when I run 
$python solve-vm.py obfuscated_binaries/tigress-0-challenge-0

it failed with following message:

  File "solve-vm.py", line 344, in <module>
    setArchitecture(ARCH.X86_64)
NameError: name 'setArchitecture' is not defined

My environment:
Ubuntu 16.04.1 LTS
Python: 2.7.14

Sincerely yours,
Jack

**Comment by JonathanSalwan** [comment]
Yes this `solve-vm.py` script is still the old API. Let me few days to update it.

**Comment by jacktang310** [comment]
Thanks for your response. I try to change it to use new API in my side. But I block at this line:
binary = Elf(sys.argv[1])
Where can I find the 'Elf' defination?
By the way , if I want to use this version solve-vm.py, which branch/tag of Triton i want to use? 
Sincerely yours,
Jack

**Comment by JonathanSalwan** [comment]
> Where can I find the 'Elf' defination?

We removed Efl and Pe parsing from Triton to use an external project ([LIEF](http://lief.quarkslab.com)).

> By the way , if I want to use this version solve-vm.py, which branch/tag of Triton i want to use?

If you want to use the current `solve-vm.py` if you have to use the Triton tag `v0.5`. Otherwise you have to update the current `solve-vm.py` to the `dev-v0.6` branch.

**Comment by JonathanSalwan** [comment]
0b0be606802f0969ab6a75572ae3abf72a4d4bc0 fixes this issue.

**Comment by jacktang310** [comment]
Hi,
   Thank you very much. I get the latest version. and try.
$./solve-vm.py ./obfuscated_binaries/tigress-0-challenge-0 

It failed at another loacation:
Traceback (most recent call last):
  File "./solve-vm.py", line 641, in <module>
    retValue  = main()
  File "./solve-vm.py", line 559, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 512, in generateLLVMExpressions
    e = tritonexprs2arybo(exprs)
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 168, in tritonexprs2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 31, in tritonast2arybo
AttributeError: 'AstNode' object has no attribute 'getChilds'

My arybo branch:   feature/exprs

Sincerely yours,
Jack

**Comment by jacktang310** [comment]
I modified one line in project arybo . It's fixed.
./arybo/tools/triton_.py: 31  
e.getChilds()  change to  e.getChildren()
