### ISSUE TITLE
ARM support question?

### ISSUE THREAD

**Issue by EMC2SLN** [JonathanSalwan/Tigress_protection#3]
Does this tool support ARM assembly language? If I want to support arm assembly, how to modify it? @JonathanSalwan

**Comment by JonathanSalwan** [comment]
> Does this tool support ARM assembly language?

No.

>  If I want to support arm assembly, how to modify it? 

Add ARM support in [Triton](https://github.com/JonathanSalwan/Triton) or use another DSE tool =).
