### ISSUE TITLE
AttributeError: type object 'AST_NODE' has no attribute 'DECIMAL'

### ISSUE THREAD

**Issue by Washi1337** [JonathanSalwan/Tigress_protection#7]
Hi,

I am trying to reproduce your experiments using the `solve-vm.py` script. 

I am running on Linux (4.19.32-1-MANJARO) and have installed the `triton` library by following the instructions on [this page](https://triton.quarkslab.com/documentation/doxygen/#install_sec). Furthermore, I installed `arybo` by cloning [the repository](https://github.com/quarkslab/arybo) and running `python2 setup.py install`.

However, when I try to run the script using:
```
python2 solve-vm.py ./tigress-challenges/tigress-0-challenge-0
```

I run into the following problem:
```
[+] Loading 0x400040 - 0x400238
[+] Loading 0x400238 - 0x400254
[+] Loading 0x400000 - 0x400f14
[+] Loading 0x601e28 - 0x602550
[+] Loading 0x601e50 - 0x601fe0
[+] Loading 0x400254 - 0x400298
[+] Loading 0x400dc4 - 0x400e08
[+] Loading 0x000000 - 0x000000
[+] Loading 0x601e28 - 0x602000
[+] Hooking printf
[+] Hooking __libc_start_main
[+] Hooking strtoul
[+] Starting emulation.
[+] __libc_start_main hooked
[+] argv[0] = ./tigress-challenges/tigress-0-challenge-0
[+] argv[1] = 1234
[+] strtoul hooked
[+] Symbolizing the strtoul return
[+] printf hooked
3035321144166078008
[+] Slicing end-point user expression
[-] Instruction not supported: 0x400539: hlt
[+] Instruction executed: 39816
[+] Unique instruction executed: 458
[+] PC len: 0
[+] Emulation done.
[+] Generating symbolic_expressions/tigress-0-challenge-0.py
[+] Converting symbolic expressions to an LLVM module...
Traceback (most recent call last):
  File "./solve-vm.py", line 760, in <module>
    retValue  = main()
  File "./solve-vm.py", line 670, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 623, in generateLLVMExpressions
    e = tritonexprs2arybo(exprs)
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 161, in tritonexprs2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 50, in tritonast2arybo
AttributeError: type object 'AST_NODE' has no attribute 'DECIMAL'
```
It seems it is able to perform most of the steps, except for generating the actual LLVM module, crashing by attempting to access a `DECIMAL` attribute supposedly defined in `AST_NODE`. Obviously it is not there which leaves me into believing I might have installed my dependencies incorrectly.

Could you perhaps shed some light in what I am doing wrong? Could it be that the script requires a specific version of the libraries and that I have installed the wrong ones? I tried installing `arybo` through `pip install arybo` instead, however these seem to result in similar errors.

Thanks in advance,
Washi

**Comment by JonathanSalwan** [comment]
https://github.com/quarkslab/arybo/pull/15/files

**Comment by Washi1337** [comment]
Thanks a lot for the very quick reply!
