### ISSUE TITLE
Failed to run inside docker container

### ISSUE THREAD

**Issue by CoolTomatos** [JonathanSalwan/Tigress_protection#8]
Hi there,

I am trying to reproduce your paper. And I remember things went alright when I tried it on Tuesday with docker.

And today I built the container again and ran into the following problem:

```
[+] Loading 0x400040 - 0x400238
[+] Loading 0x400238 - 0x400254
[+] Loading 0x400000 - 0x400f14
[+] Loading 0x601e28 - 0x602550
[+] Loading 0x601e50 - 0x601fe0
[+] Loading 0x400254 - 0x400298
[+] Loading 0x400dc4 - 0x400e08
[+] Loading 0x000000 - 0x000000
[+] Loading 0x601e28 - 0x602000
[+] Hooking printf
[+] Hooking __libc_start_main
[+] Hooking strtoul
[+] Starting emulation.
[+] __libc_start_main hooked
[+] argv[0] = tigress-challenges/tigress-0-challenge-0
[+] argv[1] = 1234
[+] strtoul hooked
[+] Symbolizing the strtoul return
[+] printf hooked
3035321144166078008
[+] Slicing end-point user expression
[-] Instruction not supported: 0x400539: hlt
[+] Instruction executed: 39816
[+] Unique instruction executed: 458
[+] PC len: 0
[+] Emulation done.
[+] Generating symbolic_expressions/tigress-0-challenge-0.py
[+] Converting symbolic expressions to an LLVM module...
Traceback (most recent call last):
  File "./solve-vm.py", line 760, in <module>
    retValue  = main()
  File "./solve-vm.py", line 670, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 623, in generateLLVMExpressions
    e = tritonexprs2arybo(exprs)
  File "/usr/local/lib/python2.7/dist-packages/arybo/tools/triton_.py", line 161, in tritonexprs2arybo
    e = tritonast2arybo(e.getAst(), True, False, context)
  File "/usr/local/lib/python2.7/dist-packages/arybo/tools/triton_.py", line 50, in tritonast2arybo
    if Ty == TAstN.INTEGER:
AttributeError: class AST_NODE has no attribute 'INTEGER'
root@a5e0fbe5778e:~/Tigress_protection# 
```

Could you please help me out? I think it might have to do with the change made to Arybo a few days ago?

Thanks in advance.

**Comment by JonathanSalwan** [comment]
Mmmmh, the workaround could be to modify the Docker in order to clone Triton from its master.

**Comment by CoolTomatos** [comment]
@JonathanSalwan thanks for the quick reply

https://github.com/JonathanSalwan/Tigress_protection/blob/e58dd461e360c9f36a97175378518f547ba6006b/Dockerfile#L32
So change the above line into`curl -o triton.zip -L https://github.com/JonathanSalwan/Triton/archive/master.zip && \`?

**Comment by JonathanSalwan** [comment]
yes for example.

**Comment by CoolTomatos** [comment]
@JonathanSalwan Thanks.
It worked again with the master version of Triton.

**Comment by CoolTomatos** [comment]
Hi @JonathanSalwan , I got another problem.
`solve-vm.py` stopped responding when running against `tigress-1-challenge-2` after printing `[+] Asking for a new input...`

**Comment by JonathanSalwan** [comment]
Some examples introduce opaque predicates. If "[+] Asking for a new input..." is a bit long, set this [variable](https://github.com/JonathanSalwan/Tigress_protection/blob/c9ed26442edcf65030a8e77a69cdeac77f100801/solve-vm.py#L29) to `True`.

**Comment by CoolTomatos** [comment]
@jjk96
